# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.extractAlnParam2 <- function(file) {
    .Call('_FastaR_extractAlnParam2', PACKAGE = 'FastaR', file)
}

.extractAlnParam <- function(file, filter, gap_thresh, maf_thresh) {
    .Call('_FastaR_extractAlnParam', PACKAGE = 'FastaR', file, filter, gap_thresh, maf_thresh)
}

.getSNPs <- function(file, n_seq, n_snp, POS) {
    .Call('_FastaR_getSNPs', PACKAGE = 'FastaR', file, n_seq, n_snp, POS)
}

.extractSNPs <- function(file, n_seq, n_snp, POS) {
    .Call('_FastaR_extractSNPs', PACKAGE = 'FastaR', file, n_seq, n_snp, POS)
}

